# Generated by Django 2.2.6 on 2019-10-10 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at'], 'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='liked_user',
            field=models.ManyToManyField(related_name='liked_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
