# Generated by Django 2.2.6 on 2019-10-08 09:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191008_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='头像'),
        ),
    ]
