# Generated by Django 2.2.6 on 2019-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='浏览次数'),
        ),
    ]
