# Generated by Django 2.2.6 on 2019-10-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_view_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_num',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='浏览次数'),
        ),
    ]
