# Generated by Django 2.2.6 on 2019-10-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
