# Generated by Django 2.2.6 on 2019-10-31 03:09

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20191031_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
